### ISSUE TITLE
imx8mn not recognized by PC 

### ISSUE THREAD

**Issue by Alvintang6** [NXPmicro/imx-uuc#14]
Hi 

We developed a customized imx8mn board.  We are using the fsl-mfgtool-initramfs with 5.4.24 generated by nxp yocto to do emmc flashing. It seems the board cannot be recognized by uuu.exe when sending the FBK command. 
following are the output from linuxrc.  
```
run utp at /dev/usb-utp0/ep0
.
uuu fastboot client 1.0.0 [built [   35.789562] read descriptors
May 30 2020 16:42:14]
Start init[   35.795380] read strings
 usb
write string
Start handle command
uuc /dev/utp
uuc 0.6 [built May 30 2020 16:42:14]
UTP: Waiting for /dev/utp to appear
```

I can also see there is a "/dev/usb-ffs/ep0" device after run commands: https://github.com/NXPmicro/mfgtools/issues/42#issuecomment-407081895
It seems the ufb already start to read the "/dev/usb-ffs/ep0" but no message was received.
However, on the PC Windows10 side ./uuu.exe -lsusb list nothing. 
 
````
Connected Known USB Devices
        Path     Chip    Pro     Vid     Pid     BcdVersion
        ==================================================
````

**Comment by nxpfrankli** [comment]
did you utp device at device manage? can you try plug and unplug usb cable?

**Comment by Alvintang6** [comment]
Hi Frank, 

Thanks for your help.
I found the reason for the USB unrecognized issue is due to the misconfiguration of the device tree. Our USB port is only used for firmware download so the USBOTG_ID is set to float. After commenting on the "usb-role-switch;" property, the UTP device can be recognized by our PC now.
